all:
	g++ *.cpp -I/home/parallels/git/ursus/src 

#common_FILES = \
#		backend/catalog/column.cpp \
#		backend/catalog/schema.cpp \
#		backend/catalog/constraint.cpp \
#		backend/catalog/manager.cpp
#
#catalog_INCLUDES = \
#-I$(srcdir)/backend/catalog
